### ISSUE TITLE
Can you please add README/Getting-started? 

### ISSUE THREAD

**Issue by gkorland** [DataGrip/redis-jdbc-driver#1]
Thanks for publishing this JDBC driver, can you please add some some documentation?

**Comment by julxxy** [comment]
+1

**Comment by Veirisa** [comment]
Hi @gkorland!

I have added a detailed README.

Please let me know if you need anything else.

**Comment by gkorland** [comment]
Thanks, looks good! I'll try to follow it.
Do you plan to publish it on Maven repository?

**Comment by Veirisa** [comment]
@gkorland 

We didn't plan to publish the driver on Maven repository.

However, if the Redis community is interested in this, then we might consider it!
