### ISSUE TITLE
Why based jedis implemented not other clients

### ISSUE THREAD

**Issue by Zhoutzzz** [DataGrip/redis-jdbc-driver#5]
Is simply, faster, or stable?

**Comment by Veirisa** [comment]
Hi @Zhoutzzz,

For the driver, we looked at two Java clients recommended by Redis - [Jedis](https://github.com/redis/jedis) and [lettuce](https://github.com/lettuce-io/lettuce-core) (see https://redis.io/resources/clients/).

Jedis was chosen from these options for two reasons:
 1. Jedis is developed by the Redis team.
 2. Jedis is designed for performance and ease of use. These properties are advantageous for the driver. There is no need to use more complex Java client - lettuce.
