### ISSUE TITLE
The driver does not work with AWS MemoryDB cluster even Redis CLI still works

### ISSUE THREAD

**Issue by thangnc** [DataGrip/redis-jdbc-driver#7]
**Describe the bug**
DataGrip throw exception as below when connect to AWS MemoryDB cluster even Redis CLI still connect and show correct version

```
Unable to get the server mode using the "INFO server" command to check if the connection mode matches the server mode.
No reachable node in cluster.
```
<img width="668" alt="Screenshot 2023-08-04 at 10 28 56" src="https://github.com/DataGrip/redis-jdbc-driver/assets/975394/37dc724f-a6ed-43be-9ccf-750309628d3b">

**Steps to Reproduce**
- Create a NAT instance to allow SSH port
- Create a MemoryDB on AWS: 1 shard 2 nodes
- Allow NAT instance connect to MemoryDB via port 6379
- Create a local tunnel `ssh -vvvv -N -L 63790:xxx.clustercfg.memorydb.ap-northeast-1.amazonaws.com:6379 xxx-bastion`
- Run Redis CLI `redis-cli --verbose -h 127.0.0.1 -p 63790`
- Check cluster info & info server

```
127.0.0.1:63790> cluster info
cluster_state:ok
```

```
127.0.0.1:63790> info server
# Server
redis_version:6.2.6
redis_git_sha1:0
redis_git_dirty:0
redis_build_id:0
redis_mode:cluster
os:Amazon MemoryDB
```
- Try to connect MemoryDB on DataGrip with host `127.0.0.1` and port `63790` and get exception
<img width="553" alt="Screenshot 2023-08-04 at 10 44 14" src="https://github.com/DataGrip/redis-jdbc-driver/assets/975394/0c9e21ee-9b57-4d13-9487-67c940b31d02">

**Platform Versions**
- Redis CLI 6.0.1
- DataGrip 2023.2 Build #DB-232.8660.111, built on July 19, 2023
- Driver 1.4 stable
- MacOS Ventura 13.0.1

**Expected behavior**
DataGrip should connect to MemoryDB as Redis CLI instead of throw the exception

**Comment by Veirisa** [comment]
Hi @thangnc!

Please take a look at the comment in this issue:
[DBE-18583](https://youtrack.jetbrains.com/issue/DBE-18583) Can't connect to Redis: "Unable to get the server mode..." 

I will likely change it to a SQLWarning instead of a SQLException in the next driver version. 
Additionally, in DataGrip, I will add a hint on what to do when this error occurs.
